/*
**DanielPitthanSilveira-ExceptionBrasil
**Data:18/09/20
**FazainclusãodofornecedornoSA2
*/
USE PROTHEUS
GO
create or alter   procedure InsertSA2(
		@A2_NOME		VARCHAR(60),
		@A2_NREDUZ		VARCHAR(50),
		@A2_EST			VARCHAR(2),
		@A2_END			VARCHAR(40),
		@A2_COD_MUN		VARCHAR(5),
		@A2_MUN			VARCHAR(30),
		@A2_CEP			VARCHAR(8),
		@A2_CGC			VARCHAR(14),
		@A2_INSCR		VARCHAR(20),
		@A2_TEL			VARCHAR(50),
		@A2_COMPLEM		VARCHAR(50),
		@A2_BAIRRO		VARCHAR(30),
		@A2_NATUREZ		VARCHAR(10),
		@A2_CONTA		VARCHAR(20),
		@R_E_C_N_O_		INT,
		@A2_COD			VARCHAR(6),
		@A2_LOJA		VARCHAR(2),
		@A2_CODPAIS		VARCHAR(5),
		@A2_PAIS		VARCHAR(3),
		@A2_TIPO		VARCHAR(1)
)
as


--AVANCA A NUMERAÇÃO ATÉ UM NÚMERO LIVRE
declare @nextCod VarChar(6) =''
EXEC SOMA1 @A2_COD ,'N', @nextCod out

DECLARE @PROXIMO_NUMERO  VarChar(6) =''
SET @PROXIMO_NUMERO = @nextCod

While Exists (select 1 from SA2010 WHERE A2_COD=@PROXIMO_NUMERO)
BEGIN 
	EXEC SOMA1 @PROXIMO_NUMERO ,'N', @nextCod out
	SET @PROXIMO_NUMERO = @nextCod
END


--FAZ O INSERT NA BASE 
insert into SA2010
			(A2_NOME ,A2_NREDUZ ,A2_EST ,A2_END ,A2_COD_MUN ,A2_MUN ,A2_CEP ,A2_CGC ,A2_INSCR ,A2_TEL
			,A2_COMPLEM, A2_BAIRRO, A2_NATUREZ, A2_CONTA, R_E_C_N_O_, A2_COD, A2_LOJA, A2_CODPAIS, A2_PAIS, A2_TIPO)
VALUES
			(@A2_NOME,@A2_NREDUZ,@A2_EST,@A2_END,@A2_COD_MUN,@A2_MUN,@A2_CEP,@A2_CGC,@A2_INSCR,@A2_TEL
			,@A2_COMPLEM,@A2_BAIRRO,@A2_NATUREZ,@A2_CONTA,@R_E_C_N_O_,@PROXIMO_NUMERO,@A2_LOJA,@A2_CODPAIS,@A2_PAIS,@A2_TIPO)


SELECT * FROM SA2010 WHERE R_E_C_N_O_=@R_E_C_N_O_

