use ColorobbiaPlataform
go
delete NFeFilesMensagens
delete NFeFiles
go


use NFeXML
go

delete FileStorange
delete NFe
delete pag
delete autXML
delete det
delete infNFe
delete EmitenteIntegrado
delete emit
delete veicTransp
delete reboque
delete vol
delete dup
delete cobr
delete fat
delete infAdic
delete obsCont
delete obsFisco
delete procRef
delete compra
delete imposto
delete ICMS
delete Signature
delete ICMS00
delete KeyInfo
delete ICMS10
delete X509Data
delete ICMS20
delete SignedInfo
delete ICMS30
delete Transform
delete Reference
delete ICMS40
delete ICMS51
delete DigestMethod
delete ICMS60
delete SignatureMethod
delete ICMS70
delete CanonicalizationMethod
delete ICMS90
delete ICMSPart
delete ICMSST
delete ICMSSN101
delete ICMSSN102
delete infNFeSupl
delete ICMSSN201
delete ICMSSN202
delete ICMSSN500
delete NFref
delete ide
delete ICMSSN900
delete enderEmit
delete dest
delete enderDest
delete retirada
delete entrega
delete IPITrib
delete IPI
delete IPINT
delete COFINS
delete ProdutoIntegrado
delete prod
delete COFINSAliq
delete comb
delete COFINSQtde
delete CIDE
delete COFINSNT
delete COFINSOutr
delete impostoDevol
delete total
delete PIS
delete retTrib
delete PISAliq
delete PISQtde
delete ICMSTot
delete PISNT
delete ISSQNtot
delete PISOutr
delete transp
delete transporta
delete retTransp
delete ICMSUFDest
